//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Argon_Dashbord_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Person
    {
        public int BusinessEntityID { get; set; }
        public int ContactTypeID { get; set; }
        public string ContactTypeName { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Suffix { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public string PasswordHash { get; set; }
        public string Gender { get; set; }
        public string ModifiedDate { get; set; }
    }
}
